#!/usr/bin/env bash

set -euo pipefail

GREEN="\033[0;32m"
YELLOW="\033[1;33m"
NC="\033[0m"

log() {
    echo -e "${GREEN}[+]${NC} $1"
}

warn() {
    echo -e "${YELLOW}[!]${NC} $1"
}

log "Checking Zsh..."

if ! command -v zsh >/dev/null 2>&1; then
    log "Installing Zsh..."
    sudo apt update
    sudo apt install -y zsh
fi

log "Creating backup directory..."

mkdir -p ~/.kali-beast/backups

TIMESTAMP=$(date +%Y%m%d-%H%M%S)

if [[ -f ~/.zshrc ]]; then
    warn "Backing up existing .zshrc"
    cp ~/.zshrc \
    ~/.kali-beast/backups/.zshrc-$TIMESTAMP
fi

if [[ -f ~/.zprofile ]]; then
    cp ~/.zprofile \
    ~/.kali-beast/backups/.zprofile-$TIMESTAMP
fi

if [[ -f ~/.zshenv ]]; then
    cp ~/.zshenv \
    ~/.kali-beast/backups/.zshenv-$TIMESTAMP
fi

log "Creating required directories..."

mkdir -p ~/.config
mkdir -p ~/.local/bin
mkdir -p ~/.local/share
mkdir -p ~/.local/share/fonts
mkdir -p ~/.cache

log "Setting Zsh as default shell..."

CURRENT_SHELL=$(basename "$SHELL")

if [[ "$CURRENT_SHELL" != "zsh" ]]; then

    ZSH_PATH=$(which zsh)

    if grep -q "$ZSH_PATH" /etc/shells; then
        chsh -s "$ZSH_PATH"
        log "Default shell changed to Zsh."
    else
        warn "Zsh not found in /etc/shells"
    fi

else
    log "Zsh already default shell."
fi

log "Creating placeholder .zshrc..."

cat > ~/.zshrc << 'EOF'
# Generated by Kali Beast
# Actual configuration applied later

export PATH="$HOME/.local/bin:$PATH"
EOF

log "Zsh setup complete."